@startuml
'https://plantuml.com/class-diagram

interface TreeInterface<V>{
    + V value()
    + TreeInterface<V> leftChild()
    + TreeInterface<V> rightChild()
}

class Tree<V>{
    + V value()
    + TreeInterface<V> leftChild()
    + TreeInterface<V> rightChild()
}

interface InsertionStrategy{
    + Response insert(V newValue, Tree<V> tree)
}

TreeInterface <|.. Tree

Tree *.. TreeInterface: leftChild/rightChild
Tree *.. InsertionStrategy: insertionStrategy

@enduml