@startuml
'https://plantuml.com/class-diagram

interface Response{
    + Boolean isSuccessful()
}

interface InsertionStrategyInterface{
    + Response insert(V newValue, Tree<V> tree)
}
class DefaultInsertionStrategy{
    + Response insert(V newValue, Tree<V> tree)
}

Response <.. InsertionStrategyInterface
InsertionStrategyInterface <|.. DefaultInsertionStrategy

@enduml