@startuml
'https://plantuml.com/class-diagram

interface AstInterface{
    + TokenInterface token()
    + AstInterface leftChild()
    + AstInterface rightChild()
}

class Ast{
    + TokenInterface token()
    + AstInterface leftChild()
    + AstInterface rightChild()
}

interface TokenInterface{
    + String name()
    + String value()
}

AstInterface <|.. Ast


Ast *.. Ast: leftChild/rightChild
Ast *.. TokenInterface: token

@enduml