@startuml
'https://plantuml.com/class-diagram

interface Response{
    + Boolean isSuccessful()
}
interface AbstractSyntaxTreeBuilderInterface{
    + Response buildAsTree()
}
class AbstractSyntaxTreeBuilder implements AbstractSyntaxTreeBuilderInterface{
    + Response buildAsTree()
}
interface AbstractSyntaxTreeRepository{
    + Response getTree()
}

interface InsertionStrategyInterface{
    + Response insert(V newValue, Tree<V> tree)
}


Response <-- AbstractSyntaxTreeBuilderInterface
AbstractSyntaxTreeBuilder *.. AbstractSyntaxTreeRepository: repository
AbstractSyntaxTreeBuilder *.. InsertionStrategyInterface: InsertionStrategy
@enduml