@startuml
'https://plantuml.com/class-diagram

interface TranspilerInterface{
    + Response transpile()
}
class DefaultTranspiler{
    + Response transpile()
}

interface TreeRepository{
    + Response getTree()
}

abstract class TranspilationVisitor{
    + Path pathToSaveTranspilation
    + Response visit(AssignationNode node)
    + Response visit(LetDeclarationNode node)
    + Response visit(LiteralNode node)
    + Response visit(TypeNode node)
    + Response visit(IdentifierNode node)
    + Response visit(EndOfLine node)
}

TranspilerInterface <|.. DefaultTranspiler

DefaultTranspiler *.. TreeRepository: repository
DefaultTranspiler *.. TranspilationVisitor: transpilerVisitor

@enduml