@startuml
'https://plantuml.com/class-diagram

interface ASTreeComponent{
    + Response addChild(ASTreeNodeInterface newChildren)
    + Response removeChild(ASTreeNodeInterface oldChildren)
    + Response getChild(Integer index)
    + Response accept(VisitorInterface visitor)
}
interface ASTreeComposite extends ASTreeComponent{
    + Response addChild(ASTreeNodeInterface newChildren)
    + Response removeChild(ASTreeNodeInterface oldChildren)
    + Response getChild(Integer index)
    + Response accept(VisitorInterface visitor)
}
interface ASTreeLeaf extends ASTreeComponent{
    + Response addChild(ASTreeNodeInterface newChildren)
    + Response removeChild(ASTreeNodeInterface oldChildren)
    + Response getChild(Integer index)
    + Response accept(VisitorInterface visitor)
}

ASTreeComposite *.. ASTreeComponent: children

@enduml