@startuml
'https://plantuml.com/class-diagram

interface AbstractSyntaxTreeComponent{
    + Response addChild(ASTreeNodeInterface newChildren)
    + Response removeChild(ASTreeNodeInterface oldChildren)
    + Response getChild(Integer index)
    + Response accept(VisitorInterface visitor)
}
abstract class AbstractSyntaxTreeComposite implements AbstractSyntaxTreeComponent{
    + Response addChild(ASTreeNodeInterface newChildren)
    + Response removeChild(ASTreeNodeInterface oldChildren)
    + Response getChild(Integer index)
    + Response accept(VisitorInterface visitor)
}
abstract class AbstractSyntaxTreeLeaf implements AbstractSyntaxTreeComponent{
    + Response addChild(ASTreeNodeInterface newChildren)
    + Response removeChild(ASTreeNodeInterface oldChildren)
    + Response getChild(Integer index)
    + Response accept(VisitorInterface visitor)
}

AbstractSyntaxTreeLeafExample *.. AbstractSyntaxTreeComponent: children

@enduml