@startuml
'https://plantuml.com/class-diagram

interface TokenInterface{
    + String name()
    + String value()
}

class Token{
    + String name
    + String value
    + String name()
    + String value()
}

TokenInterface<|..Token

@enduml