@startuml
'https://plantuml.com/class-diagram

interface Analyzer{
    + Response analyze()
}

class SemanticAnalyzer{
    + Response analyze()
}

interface TreeRepository{
    + Response getTree()
}

interface TreeValidationStrategy{
    + Response validate(Tree<V> root)
}

Analyzer <|.. SemanticAnalyzer

SemanticAnalyzer *.. TreeRepository
SemanticAnalyzer *.. TreeValidationStrategy
@enduml